name: LuaTest Workflow

on:
  push:
    branches:
      - '**' # matches every branch
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - '**'

jobs:
  build-job:
    name: ${{matrix.os}} ${{matrix.build-type}}
  
    strategy:
      fail-fast: false
      
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build-type: [Release,Debug]

    runs-on: ${{ matrix.os }}

    env:
      BUILD_TYPE: ${{ matrix.build-type }}
      JOB_NAME: ${{matrix.os}}_${{matrix.build-type}}

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git fetch --force --tags

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 8

  clean-job:
    if: always()
    needs: [build-job]
    runs-on: ubuntu-latest
    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 week'
          skip-recent: 5
          skip-tags: false
